In [10]:
import numpy as np
import cv2
import pywt
from PIL import Image

In [11]:
"quantized_image.jpg"
"Original-Lena-image.png"
img= cv2.imread("quantized_image.jpg")
cv2.namedWindow("image",cv2.WINDOW_NORMAL)
cv2.resizeWindow("image",600,400)
cv2.imshow("image",img)
cv2.waitKey(0)
cv2.destroyAllWindows()
cv2.imwrite("oimage.jpg",img)

True

In [12]:
YCrCb_img = cv2.cvtColor(img, cv2.COLOR_BGR2YCrCb)
cv2.namedWindow("image",cv2.WINDOW_NORMAL)
cv2.resizeWindow("image",600,400)
cv2.imshow("image",YCrCb_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [13]:
Thres_ratio = 0.2
y,cr,cb = cv2.split(YCrCb_img)
y_coeff = pywt.dwt2(y,'bior2.2')
cr_coeff = pywt.dwt2(cr,'bior2.2')
cb_coeff = pywt.dwt2(cb,'bior2.2')
compressed_y = pywt.threshold(y_coeff[0],Thres_ratio*np.max(y_coeff[0]), mode='soft'),pywt.threshold(y_coeff[1],Thres_ratio*np.max(y_coeff[1]), mode='soft')
compressed_cr = pywt.threshold(cr_coeff[0],Thres_ratio*np.max(cr_coeff[0]), mode='soft'), pywt.threshold(cr_coeff[1],Thres_ratio*np.max(cr_coeff[1]), mode='soft')
compressed_cb = pywt.threshold(cb_coeff[0],Thres_ratio*np.max(cb_coeff[0]), mode='soft'),pywt.threshold(cb_coeff[1],Thres_ratio*np.max(cb_coeff[1]), mode='soft')


In [14]:
uncompressed_y = np.uint8(pywt.idwt2(compressed_y, 'bior2.2'))
uncompressed_cr=np.uint8(pywt.idwt2(cr_coeff,'bior2.2'))
uncompressed_cb=np.uint8(pywt.idwt2(cb_coeff,'bior2.2'))
print(uncompressed_y)
rec = cv2.merge([uncompressed_y,uncompressed_cr,uncompressed_cb])
rec = cv2.cvtColor(rec,cv2.COLOR_YCrCb2BGR)
print(rec.shape)
print(rec.size)
print(img.size)
cv2.namedWindow("image",cv2.WINDOW_NORMAL)
cv2.resizeWindow("image",600,400)
cv2.imshow("image",rec)
cv2.waitKey(0)
cv2.destroyAllWindows()
cv2.imwrite("reconstructed.jpg",rec)

[[0 0 0 ... 3 3 3]
 [0 0 0 ... 3 3 3]
 [0 0 0 ... 3 3 3]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
(3202, 4800, 3)
46108800
46108800


True